export const products = [
    // --- Mì Gói (Pack Noodles) ---
    {
        id: "p1",
        name: "Mì Tôm Chua Cay Truyền Thống",
        description: "Hương vị quốc linh hồn của người Việt, nước súp chua cay đậm đà khó quên.",
        price: 4500,
        image: "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?q=80&w=1000&auto=format&fit=crop", // Changed to a more stable noodle shot
        category: "mi-goi",
        rating: 4.9,
        reviews: 850,
        spicyLevel: 2,
    },
    {
        id: "p2",
        name: "Mì Khoai Tây Sốt Bò Hầm",
        description: "Sợi mì làm từ khoai tây dai mướt, kết hợp sốt bò hầm rượu vang thượng hạng.",
        price: 8500,
        image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?q=80&w=1000&auto=format&fit=crop",
        category: "mi-goi",
        rating: 4.7,
        reviews: 320,
        spicyLevel: 1,
    },
    {
        id: "p3",
        name: "Mì Hải Sản Cay Cấp Độ 7",
        description: "Thách thức bản lĩnh với vị cay bùng nổ, hương vị hải sản tươi sống.",
        price: 13000,
        image: "https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?q=80&w=1000&auto=format&fit=crop",
        category: "mi-goi",
        rating: 4.8,
        reviews: 540,
        spicyLevel: 7,
    },
    // --- Mì Ly (Cup Noodles) ---
    {
        id: "p4",
        name: "Mì Ly Lẩu Thái Tomyum",
        description: "Tiện lợi mang đi, hương vị lẩu Thái chuẩn vị với tôm thật sấy khô.",
        price: 15000,
        image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?q=80&w=1000&auto=format&fit=crop",
        category: "mi-ly",
        rating: 4.6,
        reviews: 210,
        spicyLevel: 3,
    },
    {
        id: "p5",
        name: "Mì Ly Bò Hầm Tiêu Xanh",
        description: "Thơm nồng tiêu xanh, thịt bò thật hầm mềm, bữa sáng hoàn hảo.",
        price: 16000,
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=1000&auto=format&fit=crop",
        category: "mi-ly",
        rating: 4.5,
        reviews: 180,
        spicyLevel: 2,
    },
    // --- Mì Hàn Quốc (Korean Style) ---
    {
        id: "p6",
        name: "Mì Trộn Tương Đen Hoàng Gia",
        description: "Sốt tương đen Jajangmyeon chuẩn Hàn, sợi mì to dai cực đã.",
        price: 22000,
        image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=1000&auto=format&fit=crop",
        category: "mi-han-quoc",
        rating: 4.9,
        reviews: 420,
        spicyLevel: 1,
    },
    {
        id: "p7",
        name: "Mì Cay Phô Mai Tan Chảy",
        description: "Sự kết hợp béo ngậy của phô mai và vị cay nồng nàn.",
        price: 24000,
        image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?q=80&w=1000&auto=format&fit=crop",
        category: "mi-han-quoc",
        rating: 4.8,
        reviews: 300,
        spicyLevel: 4,
    },
    {
        id: "p8",
        name: "Mì Trộn Trứng Muối",
        description: "Vị trứng muối mặn mà, béo ngậy, trend mới của giới trẻ.",
        price: 18000,
        image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=1000&auto=format&fit=crop",
        category: "mi-tron",
        rating: 4.7,
        reviews: 150,
        spicyLevel: 1,
    },
];

export const categories = [
    { id: "all", name: "Tất Cả" },
    { id: "mi-goi", name: "Mì Gói" },
    { id: "mi-ly", name: "Mì Ly" },
    { id: "mi-han-quoc", name: "Mì Hàn Quốc" },
    { id: "mi-tron", name: "Mì Trộn" },
];
